
[workspace]
members = [
    "cglue",
	"cglue-gen",
	"cglue-macro",
	"examples/plugin-api",
	"examples/plugin-lib",
	"examples/user-bin"
]

default-members = [
    "cglue",
    "cglue-gen",
	"cglue-macro",
	"examples/plugin-api",
	"examples/plugin-lib",
	"examples/user-bin"
]

